### ISSUE TITLE
Missing Presentation Slides

### ISSUE THREAD

**Issue by BeckerJakob** [microsoft/aitour-ai-apps-with-scalable-database#8]
I attended today’s AI tour in Berlin and received the QR code for the presentation slides. Although the README states that the slides can be found under SESSION_RESOURCE, I’m unable to locate them. Could you please upload the presentation for this session? Thank you!

**Comment by paladique** [comment]
Hi @BeckerJakob sorry for the inconvenience, we have made the link to these slides more visible in the readme. [You can access them here](https://github.com/microsoft/aitour-ai-apps-with-scalable-database/tree/main/session-delivery-resources). Thanks for attending!
